### PR TITLE
Use Singleton to initiate class

### PR DESCRIPTION
**Pull request by tannerm**
Use existing singleton structure to initialize the class and add the correct class to the get_instance() function.

### CODE REVIEW

**Comment by tannerm** [comment]
@pippinsplugins any thoughts on this?

**Comment by tannerm** [comment]
Hey @pippinsplugins! Just bumping this again. If possible could you let me know your thoughts by Monday? I need to get back to a client on the status here.

**Comment by tannerm** [comment]
@pippinsplugins bump

**Comment by pippinsplugins** [comment]
Looks good, thanks! I'll get it deployed.

**Comment by tannerm** [comment]
Super, thanks @pippinsplugins!

**Pull request merged**
